export default actions = {
    SET_ID: 'SET_ID',
    SET_LOCATION: 'SET_LOCATION',
    ADD_POSTS: 'ADD_POSTS',
    CLONE_WITH_POSTS: 'CLONE_WITH_POSTS',
    CLONE_WITH_HOTPOSTS: 'CLONE_WITH_HOTPOSTS',
    ADD_HOT_POSTS: 'ADD_HOT_POSTS',
    LIKE: 'LIKE',
    UNLIKE: 'UNLIKE',
    ADD_POST_TO_TOP: "ADD_POST_TO_TOP",
    SET_PAGE_NAME: "SET_PAGE_NAME",
}